version: "2.3"

services:
  react-client:
    build:
      context: client
      dockerfile: ../docker/Dockerfile.client
      target: development
    image: "react-client-demo:development"
    volumes:
      - ./client:/client
    ports:
      - "3000:3000"

  api-backend:
    build:
      context: server
      dockerfile: ../docker/Dockerfile.server
    image: "api-backend-demo:development"
    volumes:
      - ./server:/server
    ports:
      - "3001:3001"
