apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-backend
  labels:
    app: api-backend
    role: api-backend
    tier: demo
spec:
  selector:
    matchLabels:
      app: api-backend
      role: api-backend
      tier: demo
  replicas: 1
  template:
    metadata:
      labels:
        app: api-backend
        role: api-backend
        tier: demo
    spec:
      containers:
      - name: api-backend-demo
        image: brianstech/api-backend-demo:latest
        imagePullPolicy: Always
        command:
          - npm
          - run
          - start
        ports:
        - containerPort: 3001
          name: http-backend
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
          limits:
            cpu: 30m
            memory: 100Mi
        readinessProbe:
          httpGet:
            path: /api/healthz
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /api/healthz
            port: 3001
          initialDelaySeconds: 50
          periodSeconds: 30
