apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-backend
spec:
  selector:
    matchLabels:
      app: api-backend
      role: api-backend
      tier: demo
  replicas: 1
  template:
    metadata:
      labels:
        app: api-backend
        role: api-backend
        tier: demo
    spec:
      containers:
      - name: api-backend-demo
        image: brianstech/api-backend-demo:latest
        command:
          - npm
          - run
          - start
        ports:
        - containerPort: 3001
          name: http-backend
        resources:
          requests:
            cpu: 20m
            memory: 100Mi
          limits:
            cpu: 50m
            memory: 200Mi
        # readinessProbe:
        # livenessProbe:
