apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-client
  labels:
    app: react-client
    role: frontend
    tier: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-client
      role: frontend
      tier: demo
  template:
    metadata:
      labels:
        app: react-client
        role: frontend
        tier: demo
    spec:
      containers:
      - name: react-client
        image: brianstech/react-client-demo:deploy
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http-client
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
          limits:
            cpu: 30m
            memory: 100Mi
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 30
