apiVersion: v1
kind: Service
metadata:
  name: react-client
  labels:
    app: react-client
    role: frontend
    tier: demo
spec:
  selector:
    app: react-client
    role: frontend
    tier: demo
  ports:
  - port: 3000
    targetPort: http-client
