apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-client
  labels:
    app: react-client
    role: frontend
    tier: demo
spec:
  selector:
    matchLabels:
      app: react-client
      role: frontend
      tier: demo
  template:
    metadata:
      labels:
        app: react-client
        role: frontend
        tier: demo
    spec:
      containers:
      - name: react-client
        image: brianstech/react-client-demo:latest
        ports:
        - containerPort: 3000
        command:
          - npm
          - run
          - start
