FROM node:8-alpine

LABEL description="Backend server"

ARG NODE_ENV=development
ENV NODE_ENV $NODE_ENV

WORKDIR /server

# install javascript dependencies
COPY package.json package.json
COPY package-lock.json package-lock.json

# ensure we install the needed dev dependencies
RUN npm --production=false install

# add server
COPY . /server
RUN if [[ "$NODE_ENV" == "production" ]]; then \
    echo "create production build" \
    && npm run build; \
    fi

EXPOSE 3001
CMD ["npm", "run", "start"]
