FROM node:8-alpine

LABEL description="Backend server"

ARG NODE_ENV=development
ENV NODE_ENV $NODE_ENV

WORKDIR /server

# install javascript dependencies
COPY package.json package.json
COPY package-lock.json package-lock.json

# ensure we install the needed dev dependencies
RUN npm install

# add server
COPY . /server

EXPOSE 3001
CMD ["npm", "run", "start"]
